AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Chromium's Serverless Application

Parameters:
  AppBucketName:
    Type: String
    Description: "REQUIRED: Unique S3 bucket name to use for the app."

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: ChromiumPDFApi
      StageName: prod
      Auth:
        ApiKeyRequired: true

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Enabled: true
      Name: MyApiKey
      StageKeys:
        - RestApiId: !Ref ApiGateway
          StageName: prod

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: MyUsagePlan
      ApiStages:
        - ApiId: !Ref ApiGateway
          Stage: prod
      Throttle:
        BurstLimit: 100
        RateLimit: 50
      Quota:
        Limit: 10000
        Period: MONTH

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

  ChromiumLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Chromium with Node.js integration for AWS Lambda
      ContentUri: layers/chromium
      CompatibleRuntimes:
        - &nodejsRuntime nodejs18.x
      # Chromium doesn't currently have ARM support; see https://github.com/Sparticuz/chromium#can-i-use-arm-or-graviton-instances
      CompatibleArchitectures:
        - &chromiumArch x86_64
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: *nodejsRuntime
      BuildArchitecture: *chromiumArch

  GeneratePdfFromHtml:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: functions/html
      Description: Generate PDFs from HTML using Chromium
      Runtime: *nodejsRuntime
      Architectures:
        - *chromiumArch
      Layers:
        - !Ref ChromiumLayer
      # Adjust as necessary
      Timeout: 30
      MemorySize: 1024
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /pdf/html
            Method: GET
      Environment:
        Variables:
          BUCKET_NAME: !Ref AppBucketName
          REGION: !Ref "AWS::Region"

  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AppBucketName
      LifecycleConfiguration:
        Rules:
          - Id: DeleteAfter24Hours
            Status: Enabled
            ExpirationInDays: 1

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:ListBucket
                  - s3:PutObjectAcl
                  - s3:GetObjectAcl
                Resource:
                  - !Sub "arn:aws:s3:::${AppBucketName}/*"
                  - !Sub "arn:aws:s3:::${AppBucketName}"

Outputs:
  ApiUrl:
    Description: "URL for API endpoint"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/"
  Region:
    Description: "AWS Region"
    Value: !Ref "AWS::Region"
  BucketName:
    Description: "Name of the S3 bucket"
    Value: !Ref AppBucketName
  BucketArn:
    Description: "ARN of the S3 bucket"
    Value: !GetAtt AppBucket.Arn
  LambdaFunctionName:
    Description: "Name of the Lambda function"
    Value: !Ref GeneratePdfFromHtml
  LambdaFunctionArn:
    Description: "ARN of the Lambda function"
    Value: !GetAtt GeneratePdfFromHtml.Arn
  RoleName:
    Description: "Name of the IAM Role"
    Value: !Ref LambdaExecutionRole
  RoleArn:
    Description: "ARN of the IAM Role"
    Value: !GetAtt LambdaExecutionRole.Arn
